name: Deploy Quarkus from master ğŸ–¥ï¸
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  get-properties:
    name: âœï¸ Retrieve application properties âœï¸
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout properties â¬‡ï¸
        uses: actions/checkout@v4
        with:
          repository: fabricalo-web/ms-properties
          token: ${{ secrets.REPO_TOKEN }}
          sparse-checkout: properties/report-ms/prd/
          sparse-checkout-cone-mode: false
      - name: â¬†ï¸ Upload properties file â¬†ï¸
        uses: actions/upload-artifact@v4
        with:
          name: report-properties
          path: properties/report-ms/prd/

  unit-tests:
    name: ğŸ“„ Unit tests ğŸ“„
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repository â¬‡ï¸
        uses: actions/checkout@v4
      - name: ğŸ’½ Set up JDK 21 ğŸ’½
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: ğŸ”“ Grant execution permits to mvnw ğŸ”“
        run: chmod +x mvnw
      - name: ğŸ“„ Execute unit tests ğŸ“„
        run: ./mvnw test

  build-image:
    name: ğŸ› ï¸ Build Docker image ğŸ› ï¸
    needs: [get-properties, unit-tests]
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repository â¬‡ï¸
        uses: actions/checkout@v4
      - name: â¬‡ï¸ Download properties file â¬‡ï¸
        uses: actions/download-artifact@v4
        with:
          name: report-properties
      - name: ğŸ’½ Set up JDK 21 ğŸ’½
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: ğŸ’½ Set up GraalVM for Native Build ğŸ’½
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          components: 'native-image'
          github-token: ${{ secrets.REPO_TOKEN }}
      - name: ğŸ“ Generate directories ğŸ“
        run: mkdir -p src/main/resources/
      - name: âœï¸ Move properties file âœï¸
        run: mv application.yml src/main/resources/application.yml
      - name: ğŸ“ Move reports directory ğŸ“
        run: mv reports src/main/resources/
      - name: ğŸ“¦ Package image ğŸ“¦
        run: ./mvnw package -Pwith-fonts -DskipTests
      - name: ğŸ› ï¸ Build Docker image ğŸ› ï¸
        run: docker build -f src/main/docker/Dockerfile.jvm -t fabricaloweb/report-generator-ms .
      - name: âœ”ï¸ Login to registry âœ”ï¸
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: â¬†ï¸ Push image to registry â¬†ï¸
        run: docker push fabricaloweb/report-generator-ms:latest

  deploy-image:
    name: ğŸ–¥ï¸ Deploy generated Docker image ğŸ–¥ï¸
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: âœ”ï¸ Login to registry âœ”ï¸
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: ğŸ’€ Kill and erase previous docker instance and image ğŸ’€
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PPK }}
          script: |
            cd /opt/docker-compose/report-generator-ms
            sudo docker compose down
            sudo docker rm fabricaloweb/report-generator-ms
            sudo docker rmi fabricaloweb/report-generator-ms
      - name: â¬‡ï¸ Pull docker image â¬‡ï¸
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PPK }}
          script: sudo docker pull fabricaloweb/report-generator-ms:latest
      - name: ğŸš€ Deploy new Docker instance ğŸš€
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PPK }}
          script: |
            cd /opt/docker-compose/report-generator-ms
            sudo docker compose up -d